// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.yuwei.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yuwei.proto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
<<<<<<< HEAD
   * <code>string realname = 1;</code>
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 1;</code>
=======
   * <code>string realname = 2;</code>
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 2;</code>
>>>>>>> refs/remotes/origin/master
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
